### ISSUE TITLE
Usando estos datos

### ISSUE THREAD

**Issue by lucasrodes** [jmcastagnetto/covid-19-peru-vacunas#2]
Buenas,
Abro este hilo únicamente para agradecerte el trabajo y informarte que ahora estamos usando estos datos en el repositorio de [owid/covid-19-data](https://github.com/owid/covid-19-data). Puedes ver el script importando los datos [aquí](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/src/vax/batch/peru.py)

Muchas gracias!

PD: Siéntase libre de cerrar el hilo al leer el mensaje

**Comment by jmcastagnetto** [comment]
Me da alegría el poder apoyar en algo en esta crisis global.

Estoy actualizando los datos, usualmente a las 22:00h (PET = 03:00h UTC) cada día, pero si por su workflow necesitan que se haga antes, me lo indicas para re-programar.

Si hay alguna otra fuente de datos de Perú con la cual necesiten una mano, no dudes en contactarme.

**Comment by lucasrodes** [comment]
Muchísimas gracias!

Solemos actualizar hacia las 11:00 UTC, así que no debería haber ningun problema.

Tomo nota para datos de Perú. Estamos en contacto.

**Comment by jmcastagnetto** [comment]
Sólo un aviso, parece que la hora a la que suben nuevos datos es variable. He cambiado ahora para que mi script local intente cada dia a las 10:00h y 22:00h PET. También, ocasionalmente algunos dias (usualmente fines de semana), no hay actualizaciones en el repositorio de datos.

**Comment by jmcastagnetto** [comment]
Acabo de ver que en los datasets mas recientes, ya aparecen las vacunas de Astra/Zeneca que se están aplicando. El CSV con los acumulados refleja eso.

**Comment by lucasrodes** [comment]
Buenísimo, se debería reflejar en el update de mañana, lo verifico. Muchas gracias @jmcastagnetto
