### ISSUE TITLE
Datos desde el 2021-07-19

### ISSUE THREAD

**Issue by lucasrodes** [jmcastagnetto/covid-19-peru-vacunas#3]
Buenas @jmcastagnetto,
En https://github.com/owid/covid-19-data usamos estos datos para Perú. En particular, usamos el fichero [vacunas_covid_resumen.csv](https://github.com/jmcastagnetto/covid-19-peru-vacunas/blob/main/datos/vacunas_covid_resumen.csv.). Hemos observado que desde el 19 de Julio no se han añadido nuevos valores[ publicados por el gobierno](https://www.gob.pe/institucion/pcm/campa%C3%B1as/3451-campana-nacional-de-vacunacion-contra-la-covid-19).

Muchas gracias!

**Comment by jmcastagnetto** [comment]
Hola @lucasrodes, parece que ha habido un cambio en la fuente, tanto en formato (ahora es un archivo .7z) como en la dirección misma del recurso. 

Por eso, el proceso de actualización que apuntaba a la dirección anterior, no estaba detectando que el archivo de origen había cambiado (corre 2 veces al día, y compara sha256sum).

Estoy revisando esto para cambiar al nuevo URL de descarga del .7z, y voy a subir una actualización manual en unas horas.

**Comment by lucasrodes** [comment]
Muchas gracias por la rápida respuesta, @jmcastagnetto.

**Comment by jmcastagnetto** [comment]
Gracias a ti por avisarme. La semana pasada no tuve oportunidad de monitorear estos datos, asi que ayuda que mas ojos vean estos datos :-)

El commit fdfaebf460c796e7ca9a5291c9a4783702b6b3c3 ya tiene los datos publicados hasta el 2021-07-25.

Saludos y felicitaciones a la gente de OWID por el artículo que han publicado en Nature.
