### ISSUE TITLE
Ultima fecha en `vacunas_covid_rangoedad_owid.csv`

### ISSUE THREAD

**Issue by lucasrodes** [jmcastagnetto/covid-19-peru-vacunas#4]
Buenas,
Actualmente usamos el archivo [vacunas_covid_rangoedad_owid.csv](https://github.com/jmcastagnetto/covid-19-peru-vacunas/blob/main/datos/vacunas_covid_rangoedad_owid.csv) para los datos de vacunación por edad.

Recién detectamos que el campo `sunday` (que entendemos es equivalente a la fecha de reporte) ha cambiado sus valores ligeramente. En concreto, la fecha más antigua es ahora `2021-02-14` (antes era `2021-02-08`). Esto no supone gran problema, pero la última fecha es ahora `2021-12-05`, lo que excede la fecha actual.

Podrías comprobar si es correcto? De serlo, nos podrías ayudar a comprender mejor el campo `sunday`?

Muchas gracias de antemano!

**Comment by jmcastagnetto** [comment]
Hola @lucasrodes, el cambio es por la definición de la semana epidemiológica que comienza el domingo (por eso `sunday`) y termina el sábado. Esto a sugerencia de un par de epidemiólogos. 

Probablemente se ma ha pasado algo en ese cambio. Lo reviso mas tarde para asegurar que el cálculo está correcto, pues se me puede haber pasado y estar calculando semanas que aún no han terminado (o comenzado). 

Gracias por el feedback :-)

**Comment by jmcastagnetto** [comment]
@lucasrodes era un off-by-one de la librería nueva que estaba usando, estoy regresando a {lubridate} que es mas consistente.
Voy a corregir esto y reproceso en la noche de Perú (GMT - 5).
También voy a revisar la agrupación por edades ahora que en Perú ya estamos vacunando de 12+ años y en enero se comienza con los de 5+ años.

**Comment by jmcastagnetto** [comment]
@lucasrodes Consulta: Sería OK con ustedes que a los datos hiciera los sgtes cambios:

- first_day_of_epiweek (en lugar de sunday)
- epi_year (año epidemiológico)
- epi_week (semana epidemiológica)
- complete_epi_week (flag: 1 = la semana está completa, 0 = la semana aún no está completa)

Podría usar last_day_of_epiweek (saturday) en caso de que eso sea mas acorde con los otros datasets que están acumulando.

Espero tu feedback al respecto para ver de implementar esos cambios.

**Comment by jmcastagnetto** [comment]
Otra consulta, como ya hay boosters, estaba pensando agregar la columna correspondiente: `people_recieving_booster_per_hundred` (dosis == 3).

Voy ha hacer una corrida con datos actualizados mas tarde, y te aviso para que lo revises, y se puedan hacer los ajustes que sean necesarios para que les sea útil.

Saludos

**Comment by lucasrodes** [comment]
Buenas @jmcastagnetto,
Gracias por tu rápida respuesta!

Te respondo a continuación

> @lucasrodes Consulta: Sería OK con ustedes que a los datos hiciera los sgtes cambios:
> 
> * first_day_of_epiweek (en lugar de sunday)
> * epi_year (año epidemiológico)
> * epi_week (semana epidemiológica)
> * complete_epi_week (flag: 1 = la semana está completa, 0 = la semana aún no está completa)
> 
> 
> Podría usar last_day_of_epiweek (saturday) en caso de que eso sea mas acorde con los otros datasets que están acumulando.
> 
> Espero tu feedback al respecto para ver de implementar esos cambios.

Es indiferente si añades más campos (como epi_year o epi_week), los filtramos sin problema. En cuanto que es mejor, first_day_of_epiweek o last_day_of_epiweek, idealmente usaríamos la última fecha de la ventana. Así de pronto entiendo sería algo como usar `last_day_of_epiweek` siempre que `complete_epi_week` sea 1, y la fecha actual (la de hoy) cuando flag = 0.


> Otra consulta, como ya hay boosters, estaba pensando agregar la columna correspondiente: people_recieving_booster_per_hundred (dosis == 3).
> 
> Voy ha hacer una corrida con datos actualizados mas tarde, y te aviso para que lo revises, y se puedan hacer los ajustes que sean necesarios para que les sea útil.
> 
> Saludos

Aún no incluimos boosters en datos por edades, pero si tenemos opción (i.e. tiempo) lo haremos, así que si lo añades perfecto.


Muchas gracias!

**Comment by jmcastagnetto** [comment]
@lucasrodes OK, `last_day_of_epiweek` it is!, y el flag `complete_epi_week` = 1, si la última fecha de vacunación de la epi week coincide con el último día de la epi week, de otro modo son datos de una semana que aún no habría terminado.

Voy a ver como poner esto de manera, y revisar dos veces para no cometer el error anterior. :smile:

**Comment by jmcastagnetto** [comment]
@lucasrodes, ya está el cambio, he documentado los campos y reprocesado con los datos hasta el 2021-12-01.

Gracias por el reporte que ayudó a mejorar el proceso.
