### ISSUE TITLE
 Posibles insosistencias en `vacunas_covid_resumen.csv`

### ISSUE THREAD

**Issue by lucasrodes** [jmcastagnetto/covid-19-peru-vacunas#5]
Buenas,
He notado que hubo cambios sustanciales en el commit https://github.com/jmcastagnetto/covid-19-peru-vacunas/commit/579c18ff098189969f5d0ab98ef62930d59e0739#diff-352d30f9aa0622a9031098d8765ad680212d16c795cbaf6b31acdbe41ec31484.

Por ello, ahora en el fichero [datos/vacunas_covid_resumen.csv](https://github.com/jmcastagnetto/covid-19-peru-vacunas/blob/main/datos/vacunas_covid_resumen.csv) se da, por ejemplo, para el día 2021-01-04 hubo 7+2=9 segundas dosis y 1 primera dosis. Siendo esta la primera fecha con registro de datos, no parece correcto que hubiese más segundas dosis que primeras.

Por otro lado, muchísimas gracias por tu espléndido trabajo!

**Comment by jmcastagnetto** [comment]
Buenos dias/tardes/noches y un Feliz Año Nuevo @lucasrodes 

Acabo de comprobar que la inconsistencia que detectaste, está aún en los datos de https://www.datosabiertos.gob.pe/dataset/vacunacion descargados hace unos minutos, donde hay mas segundas que primeras dosis:

```
$ wget -O vacunas_covid.7z https://cloud.minsa.gob.pe/s/oHF5JSLEk8KzpPW/download

$ sha1sum vacunas_covid.7z 
cb3fdefdb0943a41ff63d1f771a6d82fe8b0d8ec  vacunas_covid.7z

$ 7z e vacunas_covid.7z

$ head -1 TB_VACUNACION_COVID19.csv > test.csv

$ fgrep ",20210104," TB_VACUNACION_COVID19.csv >> test.csv 

$ cat test.csv
id_persona,id_vacunados_covid19,fecha_vacunacion,id_eess,id_centro_vacunacion,id_vacuna,id_grupo_riesgo,dosis,edad
16103102,37508850,20210104,18653,0,6,71,2,26
28103681,38213407,20210104,18653,0,6,6,2,22
10134747,29953970,20210104,6518,0,1,68,2,34
31500455,44660405,20210104,18653,0,6,71,2,22
5176035,9576669,20210104,6518,0,1,67,2,47
32241107,41398151,20210104,26540,61,6,71,2,23
19487454,20210104,20210623,18990,0,6,54,1,68
18637454,38958685,20210104,26540,61,6,71,2,21
33670379,37913502,20210104,18653,0,6,40,1,20
18425157,48761595,20210104,18653,0,6,6,2,23
19963527,21948251,20210104,18653,0,6,67,2,42
```

En esta extracción simple, hay un registro cuyo `id_vacunados_covid19` coincide con la cadena de fecha y corresponde a una fecha de vacunación distinta (2021-06-23), es fácil remover ese registro pues tiene `id_persona = '19487454'`

Haciendo un conteo rápido de primeras y segundas dosis, se encuentra que, para el 2021-01-04, se tienen 9 segundas dosis, y una (1) primeras dosis.

```
$ grep -v 19487454 test.csv | cut -d ',' -f8 | sort | uniq -c
      1 1
      9 2
      1 dosis
```

Voy a preguntar a los responsables del MINSA, con respecto a esto. Por lo que entiendo, mucho del ingreso de datos es manual desde distintos sistemas, sedes y regiones, por lo que en ocasiones tienen ingresos incorrectos y continuamente estan revisando. Como resultado de esto, siempre detecto cambios cuando mis scripts revisan y comparan semana a semana entre versiones de los datos.

Cuando tenga una respuesta de la fuente (MINSA), la registro aquí para referencia futura.

**Comment by jmcastagnetto** [comment]
@lucasrodes 

Ya tengo mas claridad en cuanto esos registros, pues pude conversar con la persona del MINSA que esta haciendo seguimiento a estos datos. 

La primera vacuna oficial de la campaña general contra el COVID-19 en Perú, se puso el 2021-02-08, por lo que los datos desde ahi en adelante deberían ser consistentes.

Los datos abiertos que está publicando el MINSA estan incluyendo fechas anteriores a ese día, y que corresponden a vacunas puestas durante los ensayos clínicos que se hicieron en el país. Esos datos no están completos aún, pues dependen de que los registren las entidades que hicieron los estudios clínicos.

Dos opciones posibles para el uso de los datos en OWID:

1. Truncan todo lo que sea anterior al 2021-02-08
2. Le agrego un campo mas al archivo de resúmen indicando si es campaña de vacunación oficial (1) o ensayo clínico (0)

Me indicas cual es sería forma mas apropiada para hacer los cambios en mi código.

**Comment by lucasrodes** [comment]
Buenas @jmcastagnetto!
Feliz año, muchas gracias por tu mensaje! Y un buenos días siempre va bien, haya sol o no 😄

Muchas gracias por investigar este issue. Truncaremos los datos a partir del 2021-02-08 para solo obtener datos ya más maduros y revisados. Igual en un futuro revisamos y añadimos datos previos.

Que tengas un muy buen día!

**Comment by jmcastagnetto** [comment]
@lucasrodes 

Por si acaso, en los últimos datos publicados por el MINSA, hay fechas de vacunación en el 2020, que corresponden a los datos de estudios clínicos, y posiblemente a vacunaciones que algunos peruanos tuvieron en el extranjero. 

Para ser consistente, estoy manteniendo esa información tal como está, sólo que hay que tomar en cuenta lo que ya habíamos visto con respecto a la primera fecha en que oficialmente se comenzó la vacunación de la población en el Peru (2021-02-08). Como referencia, este hecho se documentó en un artículo en el periódico oficial del estado peruano: https://elperuano.pe/noticia/115021-presidente-sagasti-recibio-vacuna-contra-la-covid-19

**Comment by jmcastagnetto** [comment]
El número de registros previos al 2021-02-08 es muy pequeño, en los datos descargados hoy (2022-01-05), se tienen unos 1,820 registros con fechas anteriores al 2021-02-08, de un total de 50'347,351, eso es ~0.004% de los datos.

**Comment by lucasrodes** [comment]
Muchísimas gracias! Disculpa la demora en responder.
