### ISSUE TITLE
Valor de `people_vaccinated_per_hundred` excede el 100%

### ISSUE THREAD

**Issue by lucasrodes** [jmcastagnetto/covid-19-peru-vacunas#6]
Buenas @jmcastagnetto,
Detecté que para las fechas del 2 y 9 de Abril, hay entradas que tienen valores mayores al 100% para la métrica `people_vaccinated_per_hundred` en el [fichero por edad](https://github.com/jmcastagnetto/covid-19-peru-vacunas/blob/main/datos/vacunas_covid_rangoedad_owid.csv). En concreto sería para el grupo de edades 18 - 24.

Entiendo que esto puede darse por estar vacunando a personas sin residencia en Perú, quizás? 

Igual también me sorprendió el alto indice de vacunados en este grupo de edad (18-24)! Parece que es el que va liderando.

Saludos y gracias por tu ayuda!

**Comment by jmcastagnetto** [comment]
Gracias por la detección @lucasrodes, no he podido hacer actualizaciones tan seguidas porque estabamos haciendo una mudanza internacional para ir a trabajar en una Universidad fuera de Peru. 

Con respecto a valores mayores al 100%, voy a revisar esto el fin de semana, y ver/consultar al MINSA si ya están incluyendo a los extranjeros o inmigrantes recientes vacunados en el Perú, o si la base de cálculo poblacional ha sido actualizada (estaba usando la proyección a Julio del 2021), o si hay otra cause que explique la discrepancia.

Y si, se hicieron campañas grandes para los jóvenes, inclusive con premios para la gente que asistía con el mejor o mas original disfraz, "Vacunatones", y actividades de ese tipo.

**Comment by jmcastagnetto** [comment]
@lucasrodes 

Disculpa la tardanza, pero recién he podido revisar este problema a fondo. Aparentemente los datos que estaba empleando para la población al 2022 (publicados por el MINSA y el INS) no eran los mas recientes. El archivo de datos del 2022 mas reciente, tiene datos mas actualizados, pero el archivo en si tiene algunos problemas de estructura, que tuve que resolver y al final convertir cada segmento a CSV.

Con estos datos, los valores que obtengo ahora ya no son mayores a 100% :-)

Me avisas si en algún momento se genera otro problema así, y gracias por estar atento a estos detalles.
