### ISSUE TITLE
Fichero vacío

### ISSUE THREAD

**Issue by lucasrodes** [jmcastagnetto/covid-19-peru-vacunas#8]
Buenas compañeros!
Recién vi que el fichero [vacunas_covid_resumen.csv](https://github.com/jmcastagnetto/covid-19-peru-vacunas/blob/main/datos/vacunas_covid_resumen.csv) está vacío, sólo tiene el _header_.

Saludos!

**Comment by jmcastagnetto** [comment]
Gracias por el aviso @lucasrodes,

Estoy viendo que el archivo que publicaron ayer en Datos Abiertos contiene solo los headers, por eso el proceso automático que he configurado generó un archivo vacío.

Voy a tener que poner algo de lógica para que si esto ocurre de nuevo el resto del proceso se detenga. Por ahora voy a hacer una actualización manual tan pronto publiquen los datos actualizados hoy.

Como ref: Estoy automatizando el proceso en una instancia EC2 en AWS, usando otros servicios para que prendan/apaguen la instancia al momento adecuado, y en la instancia crontabs para hacer el proceso y subirlo a github, etc.

Te aviso tan pronto tenga los datos actualizados.

**Comment by jmcastagnetto** [comment]
@lucasrodes 

OK, ya he corrido el proceso manualmente y le he agregado un check rápido que espero que detecte cuando el archivo de origen está vacío.

Saludos!

**Comment by jmcastagnetto** [comment]
Fixed in commit 54dd2fc8f728bf7d6637daee693d962822f5885f

**Comment by lucasrodes** [comment]
muchas gracias, @jmcastagnetto! <3
